// English, en-US
// This file was auto-generated by Quasalang

export default {
	ccField: `CC`,
	closeContactBtn: `Close Contact`,
	contactInformation: `Contact Information`,
	noTemplatesAvailable: `There are no templates available`,
	notes: `Notes`,
	placeholder: `Placeholder`,
	sendEmail: `Send Email`,
	sendEmailWithNotes: `Send Email With Notes`,
	sendEmailWithoutNotes: `Send Email Without Notes`,
	toField: `To`,
	toggleContactCompleted: `Toggle to verify contact completed via phone/voicemail and email`,
}