// Puerto Rico, es-PR
// This file was auto-generated by Quasalang

export default {
	ccField: `CC`,
	closeContactBtn: `Contacto Cercano`,
	contactInformation: `Información del contacto`,
	noTemplatesAvailable: `No hay plantillas disponibles.`,
	notes: `Notas`,
	placeholder: `Marcador de posición`,
	sendEmail: `Enviar correo electrónico`,
	sendEmailWithNotes: `Enviar correo electrónico con notas`,
	sendEmailWithoutNotes: `Enviar correo electrónico sin notas`,
	toField: `A`,
	toggleContactCompleted: `Alternar para verificar el contacto completado por teléfono / correo de voz y correo electrónico`,
}