const grades = [
  {
    gradeId: '1220341',
    gradeLevel: '8',
    principalName: 'Daniel Gangeri',
    principalTelephoneNumber: '(305) 822-7757',
    principalEmail: 'dangangeri@dadeschools.net',
    coordinatorName: 'Elizabeth Riol',
    coordinatorTelephoneNumber: '(305) 822-7757',
    coordinatorEmail: 'eriol5@dadeschools.net',
    scheduledAssessmentDate: 'January 24',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: false,
    isMakeup: false,
    school: {
      schoolId: '020213',
      ncesAssignedSchoolId: '120039000463',
      leaAssignedSchoolId: 'FL-13-3281',
      schoolName: 'Miami Lakes K-8 Center',
      schoolAddress: '14250 NW 67th Ave',
      schoolAddressCity: 'Hialeah',
      schoolAddressState: 'FL',
      schoolAddressZip: '33014-2940',
      schoolTelephoneNumber: '(305) 822-7757',
      ncesAssignedLeaId: '1200390',
      schoolSessionBeginDate: 'January 7'
    }
  },
  {
    gradeId: '1210521',
    gradeLevel: '4',
    principalName: 'Cynthia Clay',
    principalTelephoneNumber: '(305) 688-4605',
    principalEmail: 'cclay@dadeschools.net',
    coordinatorName: 'Tonya Moorer',
    coordinatorTelephoneNumber: '(305) 688-4605',
    coordinatorEmail: 'TMoorer@dadeschools.net',
    scheduledAssessmentDate: 'January 29',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: false,
    isMakeup: false,
    school: {
      schoolId: '020236',
      ncesAssignedSchoolId: '120039000486',
      leaAssignedSchoolId: 'FL-13-4121',
      schoolName: 'Dr. Robert B. Ingram/Opa-Locka Elementary School',
      schoolAddress: '600 Ahmad St',
      schoolAddressCity: 'Opa Locka',
      schoolAddressState: 'FL',
      schoolAddressZip: '33054-3602',
      schoolTelephoneNumber: '(305) 688-4605',
      ncesAssignedLeaId: '1200390',
      schoolSessionBeginDate: 'January 7'
    }
  },
  {
    gradeId: '1210601',
    gradeLevel: '4',
    principalName: 'Ivette Bernal-Pino',
    principalTelephoneNumber: '(305) 822-0770',
    principalEmail: 'ivettebernal@dadeschools.net',
    coordinatorName: 'Ileana Robles',
    coordinatorTelephoneNumber: '(305) 822-0770',
    coordinatorEmail: 'irobles@dadeschools.net',
    scheduledAssessmentDate: 'January 30',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: false,
    isMakeup: false,
    school: {
      schoolId: '020279',
      ncesAssignedSchoolId: '120039000529',
      leaAssignedSchoolId: 'FL-13-5601',
      schoolName: 'Twin Lakes Elementary School',
      schoolAddress: '6735 W 5th Pl',
      schoolAddressCity: 'Hialeah',
      schoolAddressState: 'FL',
      schoolAddressZip: '33012-6618',
      schoolTelephoneNumber: '(305) 822-0770',
      ncesAssignedLeaId: '1200390',
      schoolSessionBeginDate: 'January 7'
    }
  },
  {
    gradeId: '1220391',
    gradeLevel: '8',
    principalName: 'DEREK NEGRON',
    principalTelephoneNumber: '(305) 624-2652',
    principalEmail: 'dnegron@dadeschools.net',
    coordinatorName: 'Aquinas Collins',
    coordinatorTelephoneNumber: '(305) 624-2652',
    coordinatorEmail: 'aqwright@dadeschools.net',
    scheduledAssessmentDate: 'January 31',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: false,
    isMakeup: false,
    school: {
      schoolId: '020294',
      ncesAssignedSchoolId: '120039000544',
      leaAssignedSchoolId: 'FL-13-6051',
      schoolName: 'Carol City Middle School',
      schoolAddress: '3737 NW 188th St',
      schoolAddressCity: 'Miami Gardens',
      schoolAddressState: 'FL',
      schoolAddressZip: '33055-2856',
      schoolTelephoneNumber: '(305) 624-2652',
      ncesAssignedLeaId: '1200390',
      schoolSessionBeginDate: 'January 7'
    }
  },
  {
    gradeId: '1210101-makeup',
    gradeLevel: '4',
    principalName: 'Jonathan Leff',
    principalTelephoneNumber: '754-323-7550',
    principalEmail: 'jonathan.leff@browardschools.com',
    coordinatorName: 'Christine Coschignano',
    coordinatorTelephoneNumber: '(754) 323-7554',
    coordinatorEmail: 'c.coschignano@browardschools.com',
    scheduledAssessmentDate: 'February 4',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: false,
    isMakeup: true,
    school: {
      schoolId: '019790',
      ncesAssignedSchoolId: '120018003814',
      leaAssignedSchoolId: 'FL-06-3581',
      schoolName: 'Silver Shores Elementary School',
      schoolAddress: '1701 SW 160th Ave',
      schoolAddressCity: 'Miramar',
      schoolAddressState: 'FL',
      schoolAddressZip: '33027-4216',
      schoolTelephoneNumber: '(754) 323-7550',
      ncesAssignedLeaId: '1200180',
      schoolSessionBeginDate: 'January 9'
    }
  },
  {
    gradeId: '1220501',
    gradeLevel: '8',
    principalName: 'Marilyn Bernard',
    principalTelephoneNumber: '(337) 850-2699',
    principalEmail: 'jbulnes1@dadeschools.net',
    coordinatorName: 'Tom Hitchens',
    coordinatorTelephoneNumber: '(337) 850-2699',
    coordinatorEmail: 'vezewike@dadeschools.net',
    scheduledAssessmentDate: 'February 5',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    isLive: true,
    assessmentComplete: false,
    isMakeup: false,
    school: {
      schoolId: '020307',
      ncesAssignedSchoolId: '120039000560',
      leaAssignedSchoolId: 'FL-13-6351',
      schoolName: 'Dixon Middle School',
      schoolAddress: '21300 Eastern Ave',
      schoolAddressCity: 'Tampa',
      schoolAddressState: 'FL',
      schoolAddressZip: '33601-2950',
      schoolTelephoneNumber: '(337) 850-2699',
      ncesAssignedLeaId: '1200390',
      schoolSessionBeginDate: 'January 7'
    }
  },
  {
    gradeId: '1220541',
    gradeLevel: '8',
    principalName: 'Maria Median',
    principalTelephoneNumber: '(305) 557-3900',
    principalEmail: 'mmedina@dadeschools.net',
    coordinatorName: 'Maria Macias',
    coordinatorTelephoneNumber: '305-557-3900',
    coordinatorEmail: 'mmacias@dadeschools.net',
    scheduledAssessmentDate: 'February 6',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: false,
    isMakeup: false,
    school: {
      schoolId: '020311',
      ncesAssignedSchoolId: '120039000568',
      leaAssignedSchoolId: 'FL-13-6501',
      schoolName: 'Miami Lakes Middle School',
      schoolAddress: '6425 Miami Lakeway N',
      schoolAddressCity: 'Miami Lakes',
      schoolAddressState: 'FL',
      schoolAddressZip: '33014-6643',
      schoolTelephoneNumber: '(305) 557-3900',
      ncesAssignedLeaId: '1200390',
      schoolSessionBeginDate: 'January 7'
    }
  },
  {
    gradeId: '1220681',
    gradeLevel: '8',
    principalName: 'Wendy Barnett',
    principalTelephoneNumber: '305-995-3800',
    principalEmail: 'wbarnett@dadeschools.net',
    coordinatorName: 'Michelle Pardillo',
    coordinatorTelephoneNumber: '(305) 995-3800',
    coordinatorEmail: 'mpardillo@dadeschools.net',
    scheduledAssessmentDate: 'February 7',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: false,
    isMakeup: false,
    school: {
      schoolId: '020327',
      ncesAssignedSchoolId: '120039000585',
      leaAssignedSchoolId: 'FL-13-6901',
      schoolName: 'W. R. Thomas Middle School',
      schoolAddress: '13001 SW 26th St',
      schoolAddressCity: 'Miami',
      schoolAddressState: 'FL',
      schoolAddressZip: '33175-1815',
      schoolTelephoneNumber: '(305) 995-3800',
      ncesAssignedLeaId: '1200390',
      schoolSessionBeginDate: 'January 7'
    }
  },
  {
    gradeId: '1210721',
    gradeLevel: '4',
    principalName: 'Lizette O`Halloran',
    principalTelephoneNumber: '(305) 625-2008',
    principalEmail: 'lcampa@dadeschools.net',
    coordinatorName: 'Donna Quigley',
    coordinatorTelephoneNumber: '(305) 625-2008',
    coordinatorEmail: 'donnaquigley@dadeschools.net',
    scheduledAssessmentDate: 'February 8',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: false,
    isMakeup: false,
    school: {
      schoolId: '020385',
      ncesAssignedSchoolId: '120039002699',
      leaAssignedSchoolId: 'FL-13-2181',
      schoolName: 'Joella Good Elementary School',
      schoolAddress: '6350 NW 188th Ter',
      schoolAddressCity: 'Hialeah',
      schoolAddressState: 'FL',
      schoolAddressZip: '33015-4735',
      schoolTelephoneNumber: '(305) 625-2008',
      ncesAssignedLeaId: '1200390',
      schoolSessionBeginDate: 'January 7'
    }
  },
  {
    gradeId: '1210841',
    gradeLevel: '4',
    principalName: 'Yecenia Martinez',
    principalTelephoneNumber: '(305) 557-3303 ext. 2200',
    principalEmail: 'ymartinez@dadeschools.net',
    coordinatorName: 'James Jackimczuk',
    coordinatorTelephoneNumber: '(305) 557-3303 ext. 2208',
    coordinatorEmail: 'jjack1@dadeschools.net',
    scheduledAssessmentDate: 'February 12',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: false,
    isMakeup: false,
    school: {
      schoolId: '020442',
      ncesAssignedSchoolId: '120039003831',
      leaAssignedSchoolId: 'FL-13-0091',
      schoolName: 'Bob Graham Education Center',
      schoolAddress: '15901 NW 79th Ave',
      schoolAddressCity: 'Miami Lakes',
      schoolAddressState: 'FL',
      schoolAddressZip: '33016-6699',
      schoolTelephoneNumber: '(305) 557-3303',
      ncesAssignedLeaId: '1200390',
      schoolSessionBeginDate: 'January 7'
    }
  },
  {
    gradeId: '1220851',
    gradeLevel: '8',
    principalName: 'Yecenia Martinez',
    principalTelephoneNumber: '(305) 557-3303 ext. 2200',
    principalEmail: 'ymartinez@dadeschools.net',
    coordinatorName: 'James Jackimczuk',
    coordinatorTelephoneNumber: '(305) 557-3303 ext. 2208',
    coordinatorEmail: 'jjack1@dadeschools.net',
    scheduledAssessmentDate: 'February 12',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: false,
    isMakeup: false,
    school: {
      schoolId: '020442',
      ncesAssignedSchoolId: '120039003831',
      leaAssignedSchoolId: 'FL-13-0091',
      schoolName: 'Bob Graham Education Center',
      schoolAddress: '15901 NW 79th Ave',
      schoolAddressCity: 'Miami Lakes',
      schoolAddressState: 'FL',
      schoolAddressZip: '33016-6699',
      schoolTelephoneNumber: '(305) 557-3303',
      ncesAssignedLeaId: '1200390',
      schoolSessionBeginDate: 'January 7'
    }
  },
  {
    gradeId: '1220911',
    gradeLevel: '8',
    principalName: 'Cynthia Lima',
    principalTelephoneNumber: '(305) 820-8800',
    principalEmail: 'cynthialima@dadeschools.net',
    coordinatorName: 'Michelle Leon',
    coordinatorTelephoneNumber: '(305) 820-8800',
    coordinatorEmail: 'mnleon@dadeschools.net',
    scheduledAssessmentDate: 'February 13',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: false,
    isMakeup: false,
    school: {
      schoolId: '020483',
      ncesAssignedSchoolId: '120039005913',
      leaAssignedSchoolId: 'FL-13-6611',
      schoolName: 'Country Club Middle School',
      schoolAddress: '18305 NW 75th Pl',
      schoolAddressCity: 'Miami Lakes',
      schoolAddressState: 'FL',
      schoolAddressZip: '33015-2957',
      schoolTelephoneNumber: '(305) 820-8800',
      ncesAssignedLeaId: '1200390',
      schoolSessionBeginDate: 'January 7'
    }
  },
  {
    gradeId: '1220921',
    gradeLevel: '8',
    principalName: 'Marjorie Enriquez',
    principalTelephoneNumber: '305-698-8000',
    principalEmail: 'menriquez@materlakes.org',
    coordinatorName: 'Joann Felipe',
    coordinatorTelephoneNumber: '(305) 698-8000',
    coordinatorEmail: 'jfelipe@materlakes.org',
    scheduledAssessmentDate: 'February 14',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: false,
    isMakeup: false,
    school: {
      schoolId: '020486',
      ncesAssignedSchoolId: '120039006173',
      leaAssignedSchoolId: 'FL-13-6033',
      schoolName: 'Mater Academy Lakes Middle School',
      schoolAddress: '17300 NW 87th Ave',
      schoolAddressCity: 'Hialeah',
      schoolAddressState: 'FL',
      schoolAddressZip: '33015-3516',
      schoolTelephoneNumber: '(305) 512-3917',
      ncesAssignedLeaId: '1200390',
      schoolSessionBeginDate: 'January 7'
    }
  },
  {
    gradeId: '1210971',
    gradeLevel: '4',
    principalName: 'Jacqueline Arias-Gonzalez',
    principalTelephoneNumber: '3058160300',
    principalEmail: 'ariasj@dadeschools.net',
    coordinatorName: 'Kathy Bustamante',
    coordinatorTelephoneNumber: '3058160300',
    coordinatorEmail: 'kbustamante@dadeschools.net',
    scheduledAssessmentDate: 'February 19',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: false,
    isMakeup: false,
    school: {
      schoolId: '020530',
      ncesAssignedSchoolId: '120039007322',
      leaAssignedSchoolId: 'FL-13-2191',
      schoolName: 'Spanish Lake Elementary School',
      schoolAddress: '7940 NW 194th St',
      schoolAddressCity: 'Hialeah',
      schoolAddressState: 'FL',
      schoolAddressZip: '33015-6415',
      schoolTelephoneNumber: '(305) 816-0300',
      ncesAssignedLeaId: '1200390',
      schoolSessionBeginDate: 'January 7'
    }
  },
  {
    gradeId: '1210071',
    gradeLevel: '4',
    principalName: 'Monica Schlosser',
    principalTelephoneNumber: '7543235200',
    principalEmail: 'monica.schlosser@browardschools.com',
    coordinatorName: 'Linda Signorelli',
    coordinatorTelephoneNumber: '(754) 323-5200',
    coordinatorEmail: 'linda.signorelli@browardschools.com',
    scheduledAssessmentDate: 'January 22',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: true,
    isMakeup: false,
    schoolRating: 4.5,
    schoolRatingComment:
      'The NAEP team was professional and the experience was awesome',
    school: {
      schoolId: '019651',
      ncesAssignedSchoolId: '120018000229',
      leaAssignedSchoolId: 'FL-06-1211',
      schoolName: 'Cooper City Elementary School',
      schoolAddress: '5080 SW 92nd Ave',
      schoolAddressCity: 'Cooper City',
      schoolAddressState: 'FL',
      schoolAddressZip: '33328-3530',
      schoolTelephoneNumber: '(754) 323-5200',
      ncesAssignedLeaId: '1200180',
      schoolSessionBeginDate: 'January 8'
    }
  },
  {
    gradeId: '1210111',
    gradeLevel: '4',
    principalName: 'Marc Charpentier',
    principalTelephoneNumber: '(754)323-7650',
    principalEmail: 'marc.charpentier@browardschools.com',
    coordinatorName: 'Julie Padron',
    coordinatorTelephoneNumber: '(754) 323-7654',
    coordinatorEmail: 'julie.padron@browardschools.com',
    scheduledAssessmentDate: 'January 23',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    assessmentComplete: true,
    isMakeup: false,
    schoolRating: 5,
    school: {
      schoolId: '019792',
      ncesAssignedSchoolId: '120018003816',
      leaAssignedSchoolId: 'FL-06-3661',
      schoolName: 'Sunset Lakes Elementary School',
      schoolAddress: '18400 SW 25th St',
      schoolAddressCity: 'Miramar',
      schoolAddressState: 'FL',
      schoolAddressZip: '33029-2539',
      schoolTelephoneNumber: '(754) 323-7650',
      ncesAssignedLeaId: '1200180',
      schoolSessionBeginDate: 'January 8'
    }
  },
  {
    gradeId: '1210101',
    gradeLevel: '4',
    principalName: 'Jonathan Leff',
    principalTelephoneNumber: '754-323-7550',
    principalEmail: 'jonathan.leff@browardschools.com',
    coordinatorName: 'Christine Coschignano',
    coordinatorTelephoneNumber: '(754) 323-7554',
    coordinatorEmail: 'c.coschignano@browardschools.com',
    scheduledAssessmentDate: 'January 23',
    assignedFieldArea: 'T11:FL-1/6',
    assignedAssessmentCoordinator: 'Sally Richardson',
    schoolRating: 2,
    schoolRatingComment:
      'The team arrived an hour late and the assessment was delayed',
    assessmentComplete: true,
    isMakeup: false,
    school: {
      schoolId: '019790',
      ncesAssignedSchoolId: '120018003814',
      leaAssignedSchoolId: 'FL-06-3581',
      schoolName: 'Silver Shores Elementary School',
      schoolAddress: '1701 SW 160th Ave',
      schoolAddressCity: 'Miramar',
      schoolAddressState: 'FL',
      schoolAddressZip: '33027-4216',
      schoolTelephoneNumber: '(754) 323-7550',
      ncesAssignedLeaId: '1200180',
      schoolSessionBeginDate: 'January 9'
    }
  }
]

export { grades }
