name: CarWorkshop

trigger: [azure-pipelines]

pool:
  name: Linux
  
stages: 
   - stage: Build
     jobs:
       - job: build_and_test
         displayName: Build and test
         steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '7.0.x'
          - task: DotNetCoreCLI@2
            inputs:
              azureSubscription: 'pipeline-service'
              command: 'restore'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            inputs:
              azureSubscription: 'pipeline-service'
              command: 'build'
          - task: DotNetCoreCLI@2
            inputs:
              azureSubscription: 'pipeline-service'
              command: 'test' 