<template>
  <div class="col-12">
    <q-card bordered flat square>
      <q-card-section class="bg-grey-1">
        <div class="row items-center">
          <div class="col-8 text-h6 ellipsis">Student List</div>
          <q-space />
          <q-select
            v-model="studentListView"
            label="Student List View"
            :options="studentListViews"
            style="width: 400px"
            @input="onInput"
          >
          </q-select>
        </div>
      </q-card-section>
      <q-separator />
      <q-card-section>
        <div class="row q-col-gutter-md">
          <div
            v-for="student in filteredStudents"
            :key="student.studentId"
            class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-2 flex"
          >
            <student-card
              :student="student"
              :display-options="displayOptions"
            />
          </div>
        </div>
      </q-card-section>
    </q-card>
  </div>
</template>

<script>
import json from '../StudentList.json'

export default {
  components: {
    'student-card': require('components/StudentCard.vue').default
  },

  data() {
    return {
      studentListView: 'Prepare Student Login Cards',
      studentListViews: [
        'Prepare Student Login Cards',
        'Prepare Room for Group A',
        'Prepare Room for Group B',
        'Prepare Room for Group C',
        'Provide Missing Demographic Variables',
        'Locate Students',
        'All'
      ],
      displayOptions: {
        showRoom: false,
        showDemographicVariables: false,
        showAdministrationVariables: true
      },
      Students: json,
      filteredStudents: []
    }
  },

  mounted() {
    this.filteredStudents = this.Students.slice()
  },

  methods: {
    onInput(value) {
      switch (value) {
        case 'Prepare Student Login Cards':
          this.displayOptions.showRoom = false
          this.displayOptions.showDemographicVariables = false
          this.displayOptions.showAdministrationVariables = true
          this.filteredStudents = this.Students.slice()
          break
        case 'Locate Students':
          this.displayOptions.showRoom = true
          this.displayOptions.showDemographicVariables = false
          this.displayOptions.showAdministrationVariables = false
          this.filteredStudents = this.Students.slice()
          break
        default:
          this.displayOptions.showRoom = true
          this.displayOptions.showDemographicVariables = true
          this.displayOptions.showAdministrationVariables = true
          this.filteredStudents = this.Students.slice()
      }
    }
  }
}
/*
      Students: [
        {
          studentId: '0001',
          session: 'DS0801',
          lastName: 'Adams',
          firstName: 'Mark',
          room: '232',
          lineNumber: '01',
          subject: 'Math',
          ancillary: 'S',
          group: 'A',
          loginId: 'MN-89-VJ',
          monthOfBirth: '11',
          yearOfBirth: '2004',
          gender: 'Male',
          raceEthnicity: 'White, not Hispanic',
          schoolLunchStatus: 'Free lunch',
          sdStatus: 'No, not SD',
          ellStatus: 'No, not ELL'
        },
        {
          studentId: '0002',
          session: 'DS0801',
          lastName: 'Arnette',
          firstName: 'Tim',
          room: '232',
          lineNumber: '02',
          subject: 'Reading',
          ancillary: null,
          group: 'B',
          loginId: 'XG-72-JV',
          monthOfBirth: '10',
          yearOfBirth: '2004',
          gender: 'Male',
          raceEthnicity: 'Asian, not Hispanic',
          schoolLunchStatus: 'Free lunch',
          sdStatus: 'Yes, IEP',
          ellStatus: 'No, not ELL'
        },
        {
          studentId: '0003',
          session: 'DS0801',
          lastName: 'Barber',
          firstName: 'Carol',
          room: '232',
          lineNumber: '03',
          subject: 'Math',
          ancillary: 'S',
          group: 'A',
          loginId: 'LL-99-CZ',
          monthOfBirth: '12',
          yearOfBirth: '2004',
          gender: 'Female',
          raceEthnicity: 'White, not Hispanic',
          schoolLunchStatus: 'Student not eligible',
          sdStatus: 'No, not SD',
          ellStatus: 'No, not ELL'
        },
        {
          studentId: '0004',
          session: 'DS0801',
          lastName: 'Brown',
          firstName: 'Kimberly',
          room: '',
          lineNumber: '04',
          subject: 'Math',
          ancillary: 'S',
          group: 'B',
          loginId: 'FX-59-SR',
          monthOfBirth: '05',
          yearOfBirth: '2005',
          gender: 'Female',
          raceEthnicity: 'Hispanic, of any race',
          schoolLunchStatus: 'Student not eligible',
          sdStatus: 'No, not SD',
          ellStatus: 'No, not ELL'
        },
        {
          studentId: '0005',
          session: 'DS0801',
          lastName: 'Camacho',
          firstName: 'Marisol',
          room: '232',
          lineNumber: '05',
          subject: 'Math',
          ancillary: 'S',
          group: 'A',
          loginId: 'CX-66-QC',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: 'Black or African American, not Hispanic',
          schoolLunchStatus: 'Student not eligible',
          sdStatus: 'No, not SD',
          ellStatus: 'Yes, ELL'
        },
        {
          studentId: '0006',
          session: 'DS0801',
          lastName: 'Cutler',
          firstName: 'Julia',
          room: '',
          lineNumber: '06',
          subject: 'Math',
          ancillary: 'S',
          group: 'B',
          loginId: 'KW-89-ND',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: 'Hispanic, of any race',
          schoolLunchStatus: 'Student not eligible',
          sdStatus: 'No, not SD',
          ellStatus: 'Yes, ELL'
        },
        {
          studentId: '0007',
          session: 'DS0801',
          lastName: 'Dangerfield',
          firstName: 'Bobby',
          room: '232',
          lineNumber: '07',
          subject: 'Math',
          ancillary: 'S',
          group: 'A',
          loginId: 'ST-82-VQ',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: 'Black or African American, not Hispanic',
          schoolLunchStatus: 'Student not eligible',
          sdStatus: 'No, not SD',
          ellStatus: 'No, not ELL'
        },
        {
          studentId: '0008',
          session: 'DS0801',
          lastName: 'Daniels',
          firstName: 'Edmond',
          room: '',
          lineNumber: '08',
          subject: 'Reading',
          ancillary: '',
          group: 'B',
          loginId: 'LY-12-WF',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: 'White, not Hispanic',
          schoolLunchStatus: 'Student not eligible',
          sdStatus: 'No, not SD',
          ellStatus: 'No, not ELL'
        },
        {
          studentId: '0009',
          session: 'DS0801',
          lastName: 'Dragaj',
          firstName: 'Justina',
          room: '232',
          lineNumber: '09',
          subject: 'Math',
          ancillary: 'S',
          group: 'A',
          loginId: 'ZT-48-TC',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: 'White, not Hispanic',
          schoolLunchStatus: 'Student not eligible',
          sdStatus: 'No, not SD',
          ellStatus: 'No, not ELL'
        },
        {
          studentId: '0010',
          session: 'DS0801',
          lastName: 'Eaton',
          firstName: 'Kenneth',
          room: '232',
          lineNumber: '10',
          subject: 'Reading',
          ancillary: '',
          group: 'B',
          loginId: 'PF-63-LQ',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '0011',
          session: 'DS0801',
          lastName: 'Erwin',
          firstName: 'Sascha',
          room: '232',
          lineNumber: '11',
          subject: 'Math',
          ancillary: 'S',
          group: 'B',
          loginId: 'LQ-33-MQ',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '0012',
          session: 'DS0801',
          lastName: 'Evans',
          firstName: 'Krystal',
          room: '232',
          lineNumber: '12',
          subject: 'Reading',
          ancillary: '',
          group: 'B',
          loginId: 'BL-45-NM',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '0013',
          session: 'DS0801',
          lastName: 'Evanson',
          firstName: 'Sarah',
          room: '232',
          lineNumber: '13',
          subject: 'Math',
          ancillary: 'S',
          group: 'A',
          loginId: 'YP-72-CW',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '0014',
          session: 'DS0801',
          lastName: 'Fienes',
          firstName: 'Katie',
          room: '178',
          lineNumber: '14',
          subject: 'Reading',
          ancillary: '',
          group: 'B',
          loginId: 'WD-86-JH',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: '',
          schoolLunchStatus: '',
          adminStatus: 'Excluded (60)',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '0015',
          session: 'DS0801',
          lastName: 'Forster',
          firstName: 'Adrienne',
          room: '178',
          lineNumber: '15',
          subject: 'Math',
          ancillary: 'S',
          group: 'A',
          loginId: 'VS-43-TD',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Frese',
          firstName: 'Alisha',
          room: '178',
          lineNumber: '16',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Gary',
          firstName: 'Rob',
          room: '178',
          lineNumber: '17',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Hitchens',
          firstName: 'Patricia',
          room: '178',
          lineNumber: '18',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Hunter',
          firstName: 'Henry',
          room: '178',
          lineNumber: '19',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Jacobs',
          firstName: 'Lynette',
          room: '178',
          lineNumber: '20',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Kohen',
          firstName: 'Laura',
          room: '178',
          lineNumber: '21',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Lann',
          firstName: 'Manny',
          room: '178',
          lineNumber: '22',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Mayer',
          firstName: 'Daryl',
          room: '178',
          lineNumber: '23',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Myers',
          firstName: 'Mary',
          room: '178',
          lineNumber: '24',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Nelson',
          firstName: 'Diego',
          room: '178',
          lineNumber: '25',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Patterson',
          firstName: 'Dan',
          room: '178',
          lineNumber: '26',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Ramono',
          firstName: 'Maria',
          room: '178',
          lineNumber: '27',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Reynolds',
          firstName: 'Reese',
          room: '178',
          lineNumber: '28',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Female',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Ritz',
          firstName: 'Jack',
          room: '178',
          lineNumber: '29',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Sangio',
          firstName: 'Pablo',
          room: '178',
          lineNumber: '30',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Thomas',
          firstName: 'Jason',
          room: '178',
          lineNumber: '31',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Wu',
          firstName: 'Alex',
          room: '139',
          lineNumber: '32',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Yang',
          firstName: 'Kevin',
          room: '139',
          lineNumber: '33',
          subject: '',
          ancillary: '',
          group: 'A',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: 'Torres',
          firstName: 'Larissa',
          room: '',
          lineNumber: '34',
          subject: '',
          ancillary: '',
          group: '',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: '',
          firstName: '',
          room: '',
          lineNumber: '35',
          subject: '',
          ancillary: '',
          group: '',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: '',
          firstName: '',
          room: '',
          lineNumber: '36',
          subject: '',
          ancillary: '',
          group: '',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: '',
          firstName: '',
          room: '',
          lineNumber: '37',
          subject: '',
          ancillary: '',
          group: '',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: '',
          firstName: '',
          room: '',
          lineNumber: '38',
          subject: '',
          ancillary: '',
          group: '',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: '',
          firstName: '',
          room: '',
          lineNumber: '39',
          subject: '',
          ancillary: '',
          group: '',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: '',
          firstName: '',
          room: '',
          lineNumber: '40',
          subject: '',
          ancillary: '',
          group: '',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: '',
          firstName: '',
          room: '',
          lineNumber: '41',
          subject: '',
          ancillary: '',
          group: '',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: '',
          firstName: '42',
          room: '',
          lineNumber: '',
          subject: '',
          ancillary: '',
          group: '',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: '',
          firstName: '',
          room: '',
          lineNumber: '43',
          subject: '',
          ancillary: '',
          group: '',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        },
        {
          studentId: '',
          session: 'DS0801',
          lastName: '',
          firstName: '',
          room: '',
          lineNumber: '44',
          subject: '',
          ancillary: '',
          group: '',
          loginId: '',
          monthOfBirth: '',
          yearOfBirth: '',
          gender: 'Male',
          raceEthnicity: '',
          schoolLunchStatus: '',
          sdStatus: '',
          ellStatus: ''
        }
      ]
*/
</script>
